### ISSUE TITLE
Unit tests won't compile after #225

### ISSUE THREAD

**Issue by m7i-org** [Next-Flip/Momentum-Firmware#248]
### Describe the bug.

While compiling the unit tests on the latest dev I'm getting:

```
$ ./fbt FIRMWARE_APP_SET=unit_tests updater_package
...
...
	INSTALL	build/f7-firmware-C/firmware.json
	LINK	build/f7-firmware-C/firmware.elf
toolchain/x86_64-linux/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: build/f7-firmware-C/applications/services/loader/firmware_api/firmware_api.o:(.rodata._ZL13elf_api_table+0x3f1c): undefined reference to `nfc_iso15693_detect_mode'
toolchain/x86_64-linux/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: build/f7-firmware-C/applications/services/loader/firmware_api/firmware_api.o:(.rodata._ZL13elf_api_table+0x5ca4): undefined reference to `nfc_iso15693_force_1outof4'
toolchain/x86_64-linux/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: build/f7-firmware-C/applications/services/loader/firmware_api/firmware_api.o:(.rodata._ZL13elf_api_table+0x5ea4): undefined reference to `nfc_iso15693_force_1outof256'
collect2: error: ld returned 1 exit status
scons: *** [build/f7-firmware-C/firmware.elf] Error 1

********** FBT ERRORS **********
build/f7-firmware-C/firmware.elf: Error 1
```

The issue has been introduced with #225, as the compilation fails with [`5afc01a`](https://github.com/Next-Flip/Momentum-Firmware/commit/5afc01a4c31dc2df0e17b261f19334ff15ada15a) but succeeds with its parent commit [`12f9bd7`](https://github.com/Next-Flip/Momentum-Firmware/commit/12f9bd73b7182c2000ba179de0361babfa0fad26). 

### Reproduction

Create the unit test package as follows:
```
$ ./fbt FIRMWARE_APP_SET=unit_tests updater_package
```

**Comment by WillyJL** [comment]
fixed in 2c247bcb50f236f919fca489b0b87406a73137c3, thanks!
